spring.application.name=customer-service
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.file.name=customer-service.log
SERVER.PORT=8081
booking.service.url=${BOOKING_SERVICE_URL:http://localhost:8083}
jwt_secret=${JWT_SECRET}
